import { useEffect } from 'react';
import { ArrowLeft, ArrowRight, BarChart3, BookOpen, CalendarDays, Check, Clock3, FileSpreadsheet, RotateCcw, ShieldCheck, TrendingDown } from 'lucide-react';
import '../blog.css';

export interface ArticleSection { heading: string; paragraphs?: string[]; bullets?: string[]; formula?: string; }
export interface Article { slug:string; title:string; description:string; category:string; readTime:string; intro:string; sections:ArticleSection[]; related:string[]; }

export const articles: Article[] = [
 {slug:'flipkart-sales-report-analysis',title:'How to Analyze a Flipkart Sales Report',description:'A practical method for reading Flipkart sales reports, calculating realization, and finding the SKUs and dates behind revenue changes.',category:'Sales reports',readTime:'8 min read',intro:'A sales report becomes useful only when gross demand, cancellations, returns, and final sales are kept separate. This guide uses the same report fields and calculation logic supported by SellerMetric.',sections:[
  {heading:'Start with the reporting period and grain',paragraphs:['Confirm the export covers the dates and seller account you intended to review. Then identify what one row represents. Depending on the export, a row may describe an SKU on a date or another reporting grain. Do not add percentages across rows; aggregate the underlying units and amounts first.'],bullets:['Check the earliest and latest Order Date','Confirm SKU ID and Category are populated','Scan numeric columns for blanks or text values']},
  {heading:'Build a revenue waterfall',paragraphs:['Begin with Gross Units and GMV, then measure how much demand was removed by cancellations and returns. Final Sale Units and Final Sale Amount represent the realized outcome in the SellerMetric sales model.'],formula:'Net realization % = Final Sale Amount ÷ GMV × 100'},
  {heading:'Move from totals to SKU causes',paragraphs:['Portfolio totals tell you that performance changed; SKU analysis tells you why. Rank SKUs by final sale amount, then compare return and cancellation rates against the portfolio average. A high-revenue SKU with worsening leakage deserves faster investigation than a very small SKU with the same rate.'],bullets:['Revenue contribution %','Return units ÷ gross units','Cancellation units ÷ gross units','Final sale amount by SKU']},
  {heading:'Use daily trends carefully',paragraphs:['Group the report by Order Date to find revenue peaks, weak days, and return spikes. A single unusual day is a prompt to investigate—not proof of a durable trend. Compare similar weekdays and promotion periods before changing inventory or pricing.']},
  {heading:'Illustrative example',paragraphs:['Example only: GMV is ₹5,00,000 and Final Sale Amount is ₹4,10,000. Net realization is 82%. If one SKU contributes ₹38,000 of the ₹90,000 gap through returns and cancellations, that SKU should be reviewed before broad portfolio changes.']}
 ],related:['flipkart-sku-analysis','flipkart-revenue-leakage']},
 {slug:'flipkart-return-report-analysis',title:'How to Analyze a Flipkart Return Report',description:'Learn how to separate RTO and customer returns, quantify refund exposure, group return reasons, and investigate problem SKUs.',category:'Returns',readTime:'8 min read',intro:'Return analysis should separate delivery failure from post-delivery product problems. Combining them into one rate can hide whether the first action belongs to logistics, listing accuracy, packaging, or product quality.',sections:[
  {heading:'Normalize the return records',paragraphs:['Confirm each usable row has an SKU, product, quantity, price, return type, reason, status, and request date where available. Standardizing these fields makes reason and SKU comparisons consistent.']},
  {heading:'Separate RTO from customer returns',paragraphs:['SellerMetric classifies courier returns as RTO and other recognized records as customer returns. RTO indicates failed delivery; customer returns happen after the buyer receives and sends back an item. The corrective actions are different.'],formula:'RTO share of returns = RTO records ÷ all return records × 100'},
  {heading:'Measure refund exposure',paragraphs:['A useful first estimate multiplies reported price by quantity for each return record, then sums the result. Treat this as refund exposure from the fields available in the Return Report—not a complete settlement reconciliation or profit calculation.']},
  {heading:'Group reasons before acting',paragraphs:['Sort return reasons by count and share. Then inspect the leading reason within the SKUs that contribute the most returns. A portfolio-level reason may be driven by only one or two products.'],bullets:['Quality issue: inspect product batches and packaging','Wrong item or variant: audit picking and listing attributes','Not as described: compare product content with the delivered item','RTO: review delivery patterns using any location data available elsewhere']},
  {heading:'Illustrative example',paragraphs:['Example only: 200 return records contain 80 courier returns and 120 customer returns. RTO represents 40% of observed returns. If 35 of those RTO records come from one SKU, investigate that product and its delivery pattern before assuming the issue affects the full catalogue.']}
 ],related:['flipkart-rto-analysis','flipkart-revenue-leakage']},
 {slug:'flipkart-sku-analysis',title:'How to Find Your Best and Worst Flipkart SKUs',description:'Use revenue contribution, return rate, cancellation rate and concentration to evaluate Flipkart SKU performance without relying on sales volume alone.',category:'SKU analysis',readTime:'7 min read',intro:'The SKU with the most orders is not automatically the healthiest SKU. A useful product review combines scale, realized revenue, returns, cancellations, and concentration risk.',sections:[
  {heading:'Define “best” before ranking',paragraphs:['Best can mean highest final revenue, lowest leakage, fastest growth, or strongest operational reliability. SellerMetric ranks by final sale amount for revenue analysis, then shows return, cancellation, and contribution metrics beside it.']},
  {heading:'Calculate comparable rates',formula:'SKU return % = SKU return units ÷ SKU gross units × 100',paragraphs:['Use the same denominator across SKUs. Compare rates only when each SKU has enough volume to be meaningful; one return from two orders should not be treated like fifty returns from one hundred orders without context.']},
  {heading:'Create a practical priority matrix',bullets:['High revenue + low leakage: protect stock and availability','High revenue + high leakage: investigate immediately','Low revenue + low leakage: test growth opportunities carefully','Low revenue + high leakage: review whether the SKU deserves attention or delisting'],paragraphs:['This matrix prioritizes effort. It does not calculate profit because product cost and marketplace fees are not present in the supported Sales Report model.']},
  {heading:'Check category and concentration risk',paragraphs:['A category can appear healthy while one SKU carries most of its revenue. Measure the share produced by the top 20% of SKUs and by the top three SKUs. High concentration is not automatically bad, but it increases exposure to stockouts, listing issues, and sudden return spikes.']},
  {heading:'Illustrative example',paragraphs:['Example only: SKU A realizes ₹80,000 with a 6% return rate. SKU B realizes ₹95,000 with a 24% return rate. SKU B is the larger seller but may deserve the first investigation because a larger share of gross demand is not being realized.']}
 ],related:['flipkart-sales-report-analysis','flipkart-revenue-leakage']},
 {slug:'flipkart-rto-analysis',title:'Flipkart RTO Analysis: What Sellers Should Measure',description:'Understand RTO, distinguish it from customer returns, calculate RTO share, and build a practical investigation workflow for failed deliveries.',category:'RTO analysis',readTime:'7 min read',intro:'Return to Origin (RTO) describes an order that returns through the delivery process rather than a buyer returning it after delivery. It should be investigated separately from product-related customer returns.',sections:[
  {heading:'Use the right denominator',paragraphs:['SellerMetric reports RTO as a share of the return records currently loaded. That answers “what portion of my observed returns are RTO?” It is not the same as RTO divided by all shipped orders. Use a shipment-level dataset when you need a shipment-wide RTO rate.'],formula:'SellerMetric RTO share = RTO return records ÷ all loaded return records × 100'},
  {heading:'Find concentration before guessing causes',paragraphs:['Group RTO records by SKU and date. If a small group of products dominates, investigate product-specific factors. If RTO rises broadly on the same dates, logistics or campaign traffic may deserve attention. Location, payment method, and carrier analysis require those fields from other available reports; do not infer them when they are absent.']},
  {heading:'Separate symptoms from actions',bullets:['RTO concentrated in one SKU: inspect listing expectations, package characteristics, and delivery compatibility','RTO spike on specific dates: compare dispatch volume and delivery conditions','High RTO across the portfolio: combine return data with shipment or region data before deciding','Customer returns rising instead: focus on quality, content, variant accuracy, and packaging']},
  {heading:'Track changes after an intervention',paragraphs:['Record the baseline period, action date, affected SKUs, and the next comparable period. Compare like-for-like windows. A lower count with much lower sales does not necessarily mean the intervention improved delivery success.']},
  {heading:'Illustrative example',paragraphs:['Example only: RTO falls from 60 to 45 records, but total orders fall by half. The count improved while the underlying rate may have worsened. Always retain a relevant volume denominator when it is available.']}
 ],related:['flipkart-return-report-analysis','flipkart-sku-analysis']},
 {slug:'flipkart-revenue-leakage',title:'Flipkart Revenue Leakage: Where Sellers Lose Realization',description:'Identify the gap between gross marketplace demand and final realized sales using cancellation, return, SKU and category analysis.',category:'Revenue leakage',readTime:'8 min read',intro:'In SellerMetric, revenue leakage describes the part of reported GMV removed by cancellations and returns before the Final Sale Amount is reached. It is a focused sales-report view, not full payment or fee reconciliation.',sections:[
  {heading:'Define the scope correctly',paragraphs:['The supported Sales Report contains GMV, Cancellation Amount, Return Amount, and Final Sale Amount. These fields reveal demand that did not become final sales. They do not, by themselves, prove settlement underpayment or calculate profit after commission, shipping, tax, advertising, and product cost.']},
  {heading:'Calculate realization and the visible gap',formula:'Visible realization gap = GMV − Final Sale Amount',paragraphs:['Compare the gap with reported Cancellation Amount and Return Amount. Differences can reflect the report’s own definitions, timing, or adjustments. Use exact export documentation and settlement reports before treating the difference as recoverable money.']},
  {heading:'Attribute leakage to products',paragraphs:['Rank SKUs by return amount and cancellation amount, then compare each product’s contribution to total final revenue. Large absolute leakage and high percentage leakage answer different questions; review both.']},
  {heading:'Prioritize causes, not just totals',bullets:['Cancellation-heavy SKU: inspect stock accuracy and order handling','Return-heavy SKU: group return reasons and product batches','High leakage category: compare its leading SKUs rather than changing every listing','Single-day spike: check promotions, inventory events, and report timing']},
  {heading:'Illustrative example',paragraphs:['Example only: GMV is ₹10,00,000 and Final Sale Amount is ₹8,30,000, producing a visible gap of ₹1,70,000 and 83% net realization. If returns account for ₹1,10,000 and cancellations ₹50,000, investigate the remaining difference using the report definitions and supporting settlement data rather than assuming an error.']}
 ],related:['flipkart-sales-report-analysis','flipkart-return-report-analysis']}
];

const bySlug=Object.fromEntries(articles.map(a=>[a.slug,a]));
function BlogHeader(){return <header className="blog-header"><a href="/" className="blog-brand"><img src="/assets/logo-mark.png" alt=""/><span>Seller<b>Metric</b></span></a><nav><a href="/features">Features</a><a href="/how-it-works">How It Works</a><a className="active" href="/blog">Seller Guides</a><a href="/faq">FAQ</a></nav><a className="blog-cta" href="/">Analyze My Reports <ArrowRight/></a></header>}
function BlogFooter(){return <footer className="blog-footer"><div><a href="/" className="blog-brand"><img src="/assets/logo-mark.png" alt=""/><span>Seller<b>Metric</b></span></a><p>Independent, private analytics and practical educational resources for Flipkart sellers.</p></div><nav><a href="/features">Features</a><a href="/how-it-works">How It Works</a><a href="/privacy">Privacy</a><a href="/faq">FAQ</a></nav><small>© 2026 SellerMetric · Not affiliated with Flipkart.</small></footer>}
export function BlogIndexPage(){useEffect(()=>{document.title='Flipkart Seller Analytics Guides | SellerMetric'},[]);return <div className="blog-page"><BlogHeader/><main><section className="blog-index-hero"><div><span><BookOpen/> SellerMetric resource center</span><h1><em>Practical guides for</em> Flipkart seller analytics.</h1><p>Learn how to read sales and return reports, evaluate SKUs, investigate RTO, and understand the gap between gross demand and realized sales.</p></div></section><section className="blog-grid-wrap"><div className="blog-section-head"><div><small>START WITH THE DATA</small><h2>Seller analytics guides</h2></div><p>Methodology based on the report fields SellerMetric actually supports. Examples are clearly labelled and limitations are stated.</p></div><div className="blog-grid">{articles.map((a,i)=><article key={a.slug} className={i===0?'featured':''}><div className="blog-card-icon">{i===0?<BarChart3/>:i===1?<RotateCcw/>:<TrendingDown/>}</div><span>{a.category} · {a.readTime}</span><h2><a href={`/blog/${a.slug}`}>{a.title}</a></h2><p>{a.description}</p><a className="read" href={`/blog/${a.slug}`}>Read guide <ArrowRight/></a></article>)}</div></section><section className="blog-trust"><ShieldCheck/><div><h2>Methodology before marketing</h2><p>SellerMetric guides distinguish what the supported reports can show from what requires settlement, cost, shipment, advertising, or location data.</p></div><a href="/features">Review supported analytics</a></section></main><BlogFooter/></div>}
export function BlogArticlePage({slug}:{slug:string}){const article=bySlug[slug];useEffect(()=>{if(article)document.title=`${article.title} | SellerMetric`},[article]);if(!article)return null;return <div className="blog-page"><BlogHeader/><main><article className="article"><a className="article-back" href="/blog"><ArrowLeft/>All seller guides</a><header><span>{article.category}</span><h1>{article.title}</h1><p>{article.intro}</p><div className="article-meta"><span><CalendarDays/>Updated 19 August 2026</span><span><Clock3/>{article.readTime}</span><span>By Nitish Kumar</span></div></header><div className="article-layout"><aside><b>IN THIS GUIDE</b>{article.sections.map((s,i)=><a href={`#section-${i+1}`} key={s.heading}>{i+1}. {s.heading}</a>)}<div><ShieldCheck/><b>Privacy-first tool</b><small>Reports are processed in your browser.</small></div></aside><div className="article-body"><div className="article-summary"><b>What you will learn</b><p>{article.description}</p></div>{article.sections.map((section,i)=><section id={`section-${i+1}`} key={section.heading}><h2>{section.heading}</h2>{section.paragraphs?.map((p,j)=><p key={j}>{p}</p>)}{section.formula&&<div className="formula"><FileSpreadsheet/><code>{section.formula}</code></div>}{section.bullets&&<ul>{section.bullets.map(x=><li key={x}><Check/>{x}</li>)}</ul>}</section>)}<div className="article-cta"><div><b>Apply the method to your own report</b><p>SellerMetric calculates supported sales and return metrics locally in your browser.</p></div><a href="/">Analyze My Reports <ArrowRight/></a></div><section className="related"><h2>Related SellerMetric guides</h2><div>{article.related.map(slug=><a href={`/blog/${slug}`} key={slug}><span>{bySlug[slug].category}</span><b>{bySlug[slug].title}</b><ArrowRight/></a>)}</div></section><div className="article-disclaimer"><b>Scope and independence</b><p>SellerMetric is an independent analytics tool and is not affiliated with Flipkart. Examples on this page are illustrative. Confirm marketplace definitions and current account data before making business decisions.</p></div></div></div></article></main><BlogFooter/></div>}
