import { useEffect, useMemo, useRef, useState } from 'react';
import {
  ArrowLeft, ArrowRight, BarChart3, Check, ChevronDown, ChevronRight,
  CircleHelp, Database, Download, EyeOff, FileCheck2, FileSpreadsheet,
  Filter, FolderOpen, HardDrive, KeyRound, Laptop, LockKeyhole, Menu,
  MousePointer2, Search, ShieldCheck, Sparkles, TableProperties, Upload,
  WifiOff, X, Zap,
} from 'lucide-react';
import { getAcceptString, isFileSupported } from '../fileParser';
import '../features-page.css';
import '../info-pages.css';

type PageName = 'how' | 'privacy' | 'faq';
interface InfoPageProps { onFileSelect: (file: File) => void }

const mainNav = [
  ['/', 'Home', 'home'], ['/features', 'Features', 'features'],
  ['/how-it-works', 'How It Works', 'how'], ['/privacy', 'Privacy', 'privacy'], ['/faq', 'FAQ', 'faq'],
];

function SiteHeader({ active, chooseReport }: { active: string; chooseReport: () => void }) {
  const [open, setOpen] = useState(false);
  return <header className="fp-header">
    <a className="fp-brand" href="/"><img src="/assets/logo-mark.png" alt=""/><span>Seller<b>Metric</b></span></a>
    <nav className="fp-desktop-nav" aria-label="Primary navigation">{mainNav.map(([url,label,key])=><a key={url} className={active===key?'active':''} href={url}>{label}</a>)}</nav>
    <button className="fp-nav-cta" onClick={chooseReport}>Analyze My Reports <ArrowRight size={14}/></button>
    <button className="fp-menu-button" onClick={()=>setOpen(!open)} aria-expanded={open} aria-label="Toggle menu">{open?<X/>:<Menu/>}</button>
    {open&&<nav className="fp-mobile-nav">{mainNav.map(([url,label])=><a key={url} href={url}>{label}<ChevronRight/></a>)}<button onClick={chooseReport}>Analyze My Reports <ArrowRight/></button></nav>}
  </header>;
}

function SiteFooter(){return <footer className="fp-footer ip-footer"><div className="fp-shell"><a className="fp-brand" href="/"><img src="/assets/logo-mark.png" alt=""/><span>Seller<b>Metric</b></span></a><span>© 2026 SellerMetric. Built for independent sellers.</span><div><a href="/features">Features</a><a href="/how-it-works">How It Works</a><a href="/privacy">Privacy</a><a href="/faq">FAQ</a><a href="https://www.instagram.com/oyee.nitishh/" target="_blank" rel="noreferrer">@oyee.nitishh ↗</a></div></div></footer>}

function PageFrame({active, onFileSelect, children}:{active:PageName;onFileSelect:(file:File)=>void;children:React.ReactNode}){
  const input=useRef<HTMLInputElement>(null);
  useEffect(()=>{const titles={how:'How SellerMetric Works — Complete Guide',privacy:'SellerMetric Privacy — Local Browser Processing',faq:'SellerMetric FAQ — Reports, Analytics & Privacy'};document.title=titles[active];const frame=requestAnimationFrame(()=>{if(location.hash)document.getElementById(location.hash.slice(1))?.scrollIntoView()});return()=>{cancelAnimationFrame(frame);document.title='SellerMetric — Free Flipkart Seller Report Analyzer'}},[active]);
  const choose=()=>input.current?.click();
  const change=(file?:File)=>{if(!file)return;if(!isFileSupported(file)){alert('Choose a CSV, XLSX, XLS, or TSV report.');return}onFileSelect(file)};
  return <div className="fp-page ip-page"><SiteHeader active={active} chooseReport={choose}/><input ref={input} hidden type="file" accept={getAcceptString()} onChange={e=>{change(e.target.files?.[0]);e.target.value=''}}/>{children}<SiteFooter/></div>
}

function InfoHero({eyebrow,titleItalic,titleBold,description,icon:Icon}:{eyebrow:string;titleItalic:string;titleBold:string;description:string;icon:React.ElementType}){
 return <section className="ip-hero"><div className="ip-orb"/><div className="fp-shell"><a href="/" className="fp-back"><ArrowLeft size={14}/> Back to SellerMetric</a><div className="ip-hero-icon"><Icon/></div><div className="fp-eyebrow"><Sparkles size={13}/>{eyebrow}</div><h1><em>{titleItalic}</em><span>{titleBold}</span></h1><p>{description}</p></div></section>
}

const howNav=[['prepare','Prepare your report'],['upload','Upload & detection'],['processing','Private processing'],['dashboard','Read your dashboard'],['requirements','Report requirements'],['troubleshooting','Troubleshooting']];
export function HowItWorksPage({onFileSelect}:InfoPageProps){return <PageFrame active="how" onFileSelect={onFileSelect}>
 <InfoHero eyebrow="Complete workflow" titleItalic="From Flipkart export" titleBold="to decisions in seconds." description="A detailed look at how SellerMetric reads your report, identifies its type, calculates performance, and presents the right dashboard—without sending the file to a server." icon={Zap}/>
 <main className="ip-shell fp-shell"><aside className="ip-toc"><b>HOW IT WORKS</b>{howNav.map(([id,t],i)=><a href={`#${id}`} key={id}><i>{i+1}</i>{t}</a>)}<button onClick={()=>document.querySelector<HTMLInputElement>('.ip-page input[type=file]')?.click()}><Upload/>Try it with a report</button></aside><div className="ip-main">
  <section id="prepare" className="ip-section"><div className="ip-step-head"><span>01</span><div><small>BEFORE YOU BEGIN</small><h2>Prepare the right Flipkart report</h2></div></div><p className="ip-lead">SellerMetric works with standard report exports from Flipkart Seller Hub. You do not need to rearrange columns, build formulas, or save a special template.</p><div className="ip-card-grid two"><article><BarChart3/><h3>Sales Report</h3><p>Used for GMV, gross units, cancellations, returns, final sales, SKU contribution, category performance, and daily trends.</p><div className="ip-pill-row"><span>GMV</span><span>SKU ID</span><span>Order Date</span></div></article><article><FileCheck2/><h3>Return Report</h3><p>Used for RTO analysis, customer returns, refund leakage, return reasons, status, dates, and product-level investigation.</p><div className="ip-pill-row amber"><span>Return Type</span><span>Reason</span><span>SKU</span></div></article></div><div className="ip-callout"><Download/><div><b>Download from Seller Hub</b><p>Open Flipkart Seller Hub → Reports, select Sales or Returns, choose your date range, and download CSV or Excel.</p></div><a href="https://seller.flipkart.com/" target="_blank" rel="noreferrer">Open Seller Hub ↗</a></div></section>
  <section id="upload" className="ip-section"><div className="ip-step-head"><span>02</span><div><small>ONE UPLOAD</small><h2>Upload and automatic report detection</h2></div></div><p className="ip-lead">Choose a file from any Analyze My Reports button or drag it into the landing-page upload area. SellerMetric checks the extension and then inspects column headers.</p><div className="ip-flow"><div><Upload/><b>File selected</b><small>CSV, XLSX, XLS, or TSV</small></div><ChevronRight/><div><Search/><b>Headers inspected</b><small>Known report signatures</small></div><ChevronRight/><div><Filter/><b>Type detected</b><small>Sales or Return report</small></div><ChevronRight/><div><BarChart3/><b>Dashboard chosen</b><small>The correct analysis opens</small></div></div><div className="ip-code-card"><div><i/><i/><i/><span>Example detection logic</span></div><code>GMV + Gross Units + Final Sale Amount&nbsp; → &nbsp;<b>Sales Analysis</b><br/>Return Reason + Return Type + Return Status&nbsp; → &nbsp;<b>Return Analysis</b></code></div></section>
  <section id="processing" className="ip-section"><div className="ip-step-head"><span>03</span><div><small>LOCAL CALCULATION</small><h2>Your browser parses and calculates</h2></div></div><p className="ip-lead">The selected file is read by JavaScript running in your browser tab. Rows are normalized, numeric fields are calculated, and related records are grouped by SKU, category, date, or return reason.</p><div className="ip-process-list"><div><FileSpreadsheet/><span><b>1. Parse</b><small>Convert the spreadsheet into rows and columns.</small></span></div><div><TableProperties/><span><b>2. Normalize</b><small>Map report headers and convert usable values.</small></span></div><div><Database/><span><b>3. Aggregate</b><small>Group totals by SKU, category, date, and reason.</small></span></div><div><Sparkles/><span><b>4. Generate insights</b><small>Apply rules to flag risks and unusual patterns.</small></span></div></div><div className="ip-security-strip"><ShieldCheck/><div><b>No upload to an application server</b><p>The processing path stays inside the current browser session.</p></div></div></section>
  <section id="dashboard" className="ip-section"><div className="ip-step-head"><span>04</span><div><small>YOUR RESULTS</small><h2>Read the dashboard from summary to detail</h2></div></div><p className="ip-lead">The dashboard is intentionally layered. Start with business-wide KPIs, then use charts and tables to identify the products or return reasons behind the totals.</p><div className="ip-dashboard-map"><div className="wide"><b>Executive KPIs</b><small>GMV · Units · Realization · Returns</small></div><div><b>Visual trends</b><small>Revenue and leakage charts</small></div><div><b>SKU tables</b><small>Product-level rates</small></div><div><b>Category analysis</b><small>Contribution and risk</small></div><div><b>Automated insights</b><small>Flags needing attention</small></div></div><ol className="ip-number-list"><li><span>1</span><div><b>Confirm the portfolio totals</b><p>Check that the report period and totals match the export you intended to analyze.</p></div></li><li><span>2</span><div><b>Look for leakage and concentration</b><p>Compare gross demand against returns, cancellations, and realized revenue.</p></div></li><li><span>3</span><div><b>Investigate individual products</b><p>Use SKU tables, filters, and return drill-downs to find the cause.</p></div></li></ol></section>
  <section id="requirements" className="ip-section"><div className="ip-step-head"><span>05</span><div><small>COMPATIBILITY</small><h2>Required report fields</h2></div></div><div className="ip-schema"><div><h3>Sales report headers</h3>{['SKU ID','Category','Order Date','Gross Units','GMV','Cancellation Units / Amount','Return Units / Amount','Final Sale Units / Amount'].map(x=><span key={x}><Check/>{x}</span>)}</div><div><h3>Return report headers</h3>{['SKU','Product','Total Price','Quantity','Return Requested Date','Return Type','Return Reason / Sub-reason','Return Status'].map(x=><span key={x}><Check/>{x}</span>)}</div></div><p className="ip-note">Column order does not matter. Header names should come from a standard Flipkart export; the return parser also accepts common header variations.</p></section>
  <section id="troubleshooting" className="ip-section"><div className="ip-step-head"><span>06</span><div><small>IF SOMETHING LOOKS WRONG</small><h2>Quick troubleshooting</h2></div></div><div className="ip-trouble"><article><b>The file is rejected</b><p>Confirm that its extension is CSV, XLSX, XLS, or TSV and that the file is not password-protected.</p></article><article><b>The wrong dashboard opens</b><p>Check whether the file contains standard report headers. Detection relies on recognizable Sales or Return columns.</p></article><article><b>Metrics are zero</b><p>Open the report and confirm numeric columns contain values rather than blank cells or non-standard text.</p></article><article><b>Mobile tables feel dense</b><p>Charts and summaries are responsive, but wide SKU tables are easier to explore on a laptop or desktop.</p></article></div></section>
 </div></main><BottomCta onClick={()=>document.querySelector<HTMLInputElement>('.ip-page input[type=file]')?.click()}/>
 </PageFrame>}

const privacyNav=[['promise','Privacy promise'],['data-flow','Data flow'],['processed','What is processed'],['not-collected','What is not collected'],['storage','Storage & retention'],['third-parties','Third parties'],['control','Your control']];
export function PrivacyPage({onFileSelect}:InfoPageProps){return <PageFrame active="privacy" onFileSelect={onFileSelect}>
 <InfoHero eyebrow="Privacy architecture" titleItalic="Your business data" titleBold="belongs to you." description="SellerMetric is designed to analyze reports locally in your browser. This page explains exactly what the tool reads, what it does not collect, and what remains under your control." icon={LockKeyhole}/>
 <main className="ip-shell fp-shell"><aside className="ip-toc"><b>PRIVACY GUIDE</b>{privacyNav.map(([id,t],i)=><a href={`#${id}`} key={id}><i>{i+1}</i>{t}</a>)}<div className="ip-toc-safe"><WifiOff/><b>No report upload</b><small>Files remain in the browser session.</small></div></aside><div className="ip-main">
  <section id="promise" className="ip-section"><div className="ip-step-head shield"><span><ShieldCheck/></span><div><small>THE SHORT VERSION</small><h2>Private by design, not by promise alone</h2></div></div><p className="ip-lead">SellerMetric does not need an account, email address, or cloud file upload to generate analytics. The core parser and calculation logic execute on your device.</p><div className="ip-commitments"><article><Check/><b>Local processing</b><p>Your report is read inside the active browser tab.</p></article><article><Check/><b>No account required</b><p>You can analyze a report without registering.</p></article><article><Check/><b>No report database</b><p>SellerMetric does not create a server-side copy of the report.</p></article><article><Check/><b>Session-based results</b><p>Close or reset the page to clear the current analysis.</p></article></div></section>
  <section id="data-flow" className="ip-section"><div className="ip-step-head"><span>01</span><div><small>DATA FLOW</small><h2>Where your report goes</h2></div></div><div className="ip-private-flow"><div><Laptop/><b>Your device</b><small>You select a local report</small></div><ArrowRight/><div className="active"><FileSpreadsheet/><b>Your browser tab</b><small>Parsing and calculations run here</small></div><ArrowRight/><div className="blocked"><X/><b>No app server</b><small>Report contents are not transmitted</small></div></div><div className="ip-callout blue"><WifiOff/><div><b>Internet connection is not used for report processing</b><p>Once the application assets are loaded, calculations are performed by code running in the browser.</p></div></div></section>
  <section id="processed" className="ip-section"><div className="ip-step-head"><span>02</span><div><small>LOCAL USE</small><h2>What the browser processes</h2></div></div><p className="ip-lead">To create the dashboard, the application reads the report fields needed for aggregation and display.</p><div className="ip-data-table"><div className="head"><span>Data category</span><span>Why it is read</span><span>Where it is used</span></div><div><b>SKU and product fields</b><span>Group product performance</span><em>SKU tables and drill-downs</em></div><div><b>Revenue and unit fields</b><span>Calculate KPIs and leakage</span><em>Summary cards and charts</em></div><div><b>Dates and categories</b><span>Build trends and breakdowns</span><em>Daily and category analysis</em></div><div><b>Return fields</b><span>Measure RTO, reasons, and refunds</span><em>Return dashboard</em></div></div></section>
  <section id="not-collected" className="ip-section"><div className="ip-step-head"><span>03</span><div><small>DATA MINIMIZATION</small><h2>What SellerMetric does not ask for</h2></div></div><div className="ip-not-list"><div><EyeOff/><span><b>No account profile</b><small>No name, company profile, login, or email is needed.</small></span></div><div><KeyRound/><span><b>No Flipkart credentials</b><small>Never enter your Seller Hub password or authentication details.</small></span></div><div><Database/><span><b>No uploaded-report archive</b><small>Reports are not kept in an application database for later retrieval.</small></span></div><div><FolderOpen/><span><b>No automatic device access</b><small>The browser only reads a file after you explicitly select or drop it.</small></span></div></div></section>
  <section id="storage" className="ip-section"><div className="ip-step-head"><span>04</span><div><small>RETENTION</small><h2>Storage and session lifecycle</h2></div></div><div className="ip-lifecycle"><div><span>1</span><b>Select</b><small>You choose a report</small></div><i/><div><span>2</span><b>Analyze</b><small>Results live in memory</small></div><i/><div><span>3</span><b>Reset or close</b><small>The active analysis is cleared</small></div></div><p className="ip-note">Downloaded browser files and the original report remain subject to your own device, browser, backup, and operating-system settings. SellerMetric cannot manage files outside the webpage.</p></section>
  <section id="third-parties" className="ip-section"><div className="ip-step-head"><span>05</span><div><small>EXTERNAL SERVICES</small><h2>Links and third-party destinations</h2></div></div><p className="ip-lead">The site includes optional links to Flipkart Seller Hub and the creator’s Instagram profile. Opening an external link takes you to a separate service with its own privacy practices.</p><div className="ip-boundary"><div><ShieldCheck/><b>Inside SellerMetric</b><small>Local report parsing and analytics</small></div><div className="line"><span>Privacy boundary</span></div><div><ArrowRight/><b>External links</b><small>Separate website policies apply</small></div></div></section>
  <section id="control" className="ip-section"><div className="ip-step-head"><span>06</span><div><small>YOUR CHOICES</small><h2>How to stay in control</h2></div></div><ul className="ip-control-list"><li><Check/><div><b>Use reports from a trusted device</b><p>Avoid analyzing sensitive business files on shared or public computers.</p></div></li><li><Check/><div><b>Check the browser address</b><p>Confirm you are using the official SellerMetric domain before selecting a report.</p></div></li><li><Check/><div><b>Close or reset after analysis</b><p>Use Back/Reset or close the tab when you finish reviewing the dashboard.</p></div></li><li><Check/><div><b>Protect the original file</b><p>Store downloaded seller reports according to your own access and backup policy.</p></div></li></ul><div className="ip-contact-card"><CircleHelp/><div><b>Questions about privacy?</b><p>Contact the creator directly through the linked Instagram profile.</p></div><a href="https://www.instagram.com/oyee.nitishh/" target="_blank" rel="noreferrer">@oyee.nitishh ↗</a></div></section>
 </div></main>
 </PageFrame>}

const faqItems=[
 ['Getting started','What is SellerMetric?','SellerMetric is a browser-based analytics tool for Flipkart sellers. It converts standard Sales and Return report exports into KPIs, charts, product tables, leakage analysis, and automated observations.'],
 ['Getting started','Is SellerMetric free?','Yes. The current tool can be used without creating an account, providing an email address, or paying a subscription fee.'],
 ['Getting started','Do I need spreadsheet skills?','No. Upload the original report export and SellerMetric handles parsing, grouping, calculations, and visualization automatically.'],
 ['Reports','Which reports are supported?','SellerMetric supports standard Flipkart Sales Reports and Return Reports. The report type is detected from its column headers.'],
 ['Reports','Which file formats can I upload?','CSV, XLSX, XLS, and TSV files are supported. Password-protected or structurally modified spreadsheets may not parse correctly.'],
 ['Reports','Which Sales Report columns are expected?','Common required fields include SKU ID, Category, Order Date, Gross Units, GMV, Cancellation Units and Amount, Return Units and Amount, and Final Sale Units and Amount.'],
 ['Reports','Which Return Report columns are expected?','Common fields include SKU, Product, Total Price, Quantity, Return Requested Date, Return Type, Return Reason, Return Sub-reason, and Return Status.'],
 ['Analysis','What does the Sales dashboard calculate?','It calculates gross units, GMV, cancellation and return totals, final sale values, net realization, SKU and category contribution, daily trends, concentration, and flagged products.'],
 ['Analysis','What does the Return dashboard calculate?','It shows total returns, refund leakage, RTO and customer-return split, average refund, top reasons, daily return trends, product-level return metrics, and rule-based insights.'],
 ['Analysis','Are the automated insights generated by AI?','The current insights are deterministic rules based on calculated metrics. They flag conditions such as high RTO share, dominant return reasons, unusually concentrated return volume, and revenue dependency.'],
 ['Analysis','Can I analyze both Sales and Return data?','Yes. Upload either report first; the appropriate dashboard opens automatically. You can then load the other report from within the dashboard and switch between Sales and Return tabs.'],
 ['Privacy','Is my report uploaded to a server?','No. Report parsing and calculations happen locally inside the browser. SellerMetric does not create a server-side copy of the uploaded report.'],
 ['Privacy','Does SellerMetric require my Flipkart login?','No. Never enter your Flipkart password into SellerMetric. Download the report yourself from Seller Hub and select the local file.'],
 ['Privacy','How do I clear the analyzed data?','Use the Back or Reset control, upload a different report, refresh the application, or close the browser tab.'],
 ['Troubleshooting','Why was my report rejected?','Check that the extension is CSV, XLSX, XLS, or TSV. Also confirm the file is not password-protected and contains a standard header row.'],
 ['Troubleshooting','Why are some values zero or missing?','The exported report may contain blank values, modified headers, text in numeric columns, or a report structure that differs from the standard Flipkart format.'],
 ['Troubleshooting','Does it work on a phone?','Yes, the navigation, summary cards, and charts are responsive. Large SKU and category tables are more comfortable to review on a tablet, laptop, or desktop.'],
 ['Troubleshooting','Is SellerMetric affiliated with Flipkart?','No. SellerMetric is an independent tool. Flipkart is a trademark of Flipkart Private Limited.'],
];
export function FaqPage({onFileSelect}:InfoPageProps){const[query,setQuery]=useState('');const[category,setCategory]=useState('All');const[open,setOpen]=useState<number|null>(0);const cats=['All',...Array.from(new Set(faqItems.map(x=>x[0])))];const filtered=useMemo(()=>faqItems.map((x,i)=>({x,i})).filter(({x})=>(category==='All'||x[0]===category)&&(`${x[1]} ${x[2]}`.toLowerCase().includes(query.toLowerCase()))),[query,category]);return <PageFrame active="faq" onFileSelect={onFileSelect}>
 <InfoHero eyebrow="Help center" titleItalic="Questions, answered" titleBold="before your first upload." description="Find detailed guidance about supported reports, calculations, privacy, troubleshooting, and the best way to use SellerMetric." icon={CircleHelp}/>
 <main className="ip-faq-main fp-shell"><div className="ip-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search questions, reports, metrics, or privacy…"/>{query&&<button onClick={()=>setQuery('')}><X/></button>}</div><div className="ip-category-row">{cats.map(c=><button className={category===c?'active':''} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</div><div className="ip-faq-layout"><aside><b>QUICK LINKS</b><a href="/how-it-works"><Zap/>How SellerMetric works<ChevronRight/></a><a href="/features"><BarChart3/>Explore every feature<ChevronRight/></a><a href="/privacy"><LockKeyhole/>Read the privacy guide<ChevronRight/></a><div><ShieldCheck/><b>Still need help?</b><small>Contact the creator on Instagram.</small><a href="https://www.instagram.com/oyee.nitishh/" target="_blank" rel="noreferrer">@oyee.nitishh ↗</a></div></aside><div className="ip-faq-list">{filtered.length?<>{filtered.map(({x,i})=><article className={open===i?'open':''} key={i}><button onClick={()=>setOpen(open===i?null:i)}><span><small>{x[0]}</small><b>{x[1]}</b></span><ChevronDown/></button><div><p>{x[2]}</p></div></article>)}</>:<div className="ip-no-results"><Search/><h3>No matching questions</h3><p>Try a broader term or choose another category.</p><button onClick={()=>{setQuery('');setCategory('All')}}>Clear filters</button></div>}</div></div><section className="ip-faq-cta"><div><Sparkles/><span><b>Ready to analyze a real report?</b><small>The dashboard is the fastest way to understand what SellerMetric can show.</small></span></div><button onClick={()=>document.querySelector<HTMLInputElement>('.ip-page input[type=file]')?.click()}>Analyze My Reports <ArrowRight/></button></section></main>
 </PageFrame>}

function BottomCta({onClick}:{onClick:()=>void}){return <section className="ip-bottom-cta"><div className="fp-shell"><div className="fp-eyebrow">Free · Private · Instant</div><h2><em>Ready to see the workflow</em><span>with your own report?</span></h2><p>Upload a standard Flipkart Sales or Return report and let SellerMetric build the right dashboard.</p><button className="fp-primary" onClick={onClick}><Upload/>Analyze My Reports<ArrowRight/></button></div></section>}
